/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData amigo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jornal = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podio = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData relogio = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cliente = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diretoria = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clima_normal = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData primeiro = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData segundo = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terceiro = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
